### ISSUE TITLE
展示更多单集

### ISSUE THREAD

**Issue by eeee0717** [LGiki/cosmos-enhanced#1]
主播界面最多展示15个单集，是否有方法可以展示更多的单集？
![CleanShot 2024-02-17 at 12 39 15@2x](https://github.com/LGiki/cosmos-enhanced/assets/70054568/e01a5c0a-8b67-461d-b728-7a33e479191b)

**Comment by LGiki** [comment]
没办法。
小宇宙网页端采用 [Server-side Rendering](https://nextjs.org/docs/pages/building-your-application/rendering/server-side-rendering)，单集数据是在服务端获取完成之后直接返回的，而不是在浏览器端请求 API 接口得到，浏览器端没办法调整页面要展示的单集数量。
