### ISSUE TITLE
现在无法下载了吗啊？

### ISSUE THREAD

**Issue by coastguardsman** [LGiki/cosmos-enhanced#3]
我现在点击任何下载相关的键，都没有反应诶

**Comment by LGiki** [comment]
我刚刚测试了一下可以正常下载，麻烦提供一下你的操作系统、浏览器、插件版本以及具体的播客或单集链接，我看看

**Comment by coastguardsman** [comment]
操作系统是macOS Catalina 10.15.7
浏览器是Chrome
插件版本是应该是最新的吧，我刚安装。
具体播客单集链接是https://www.xiaoyuzhoufm.com/episode/66d09be4d06ec988f2cbb2ad?s=eyJ1IjogIjYwMGU0NDUxZTBmNWU3MjNiYmI4YmQ0YiJ9 <https://www.xiaoyuzhoufm.com/episode/66d09be4d06ec988f2cbb2ad?s=eyJ1IjogIjYwMGU0NDUxZTBmNWU3MjNiYmI4YmQ0YiJ9>
麻烦您了！

**Comment by LGiki** [comment]
我测试了一下，我可以正常下载这个单集的音频文件及封面：

<img width="320" alt="image" src="https://github.com/user-attachments/assets/b6498b13-cd0c-43aa-a27c-39cf7a86c52d">

我观察到这个单集的标题中含有冒号`:`，该字符在 macOS 的大部分应用中作为文件名是无效字符（它会被自动转换为`/`，导致文件名不合法），在插件的早期版本中未过滤无效字符，所以会导致点击下载按钮没有反应，我猜有可能是这个原因。

所以麻烦你检查一下插件的版本是否为 `1.0.0.5`，在 Chrome 的插件管理页面可以查看插件的版本号。

**Comment by coastguardsman** [comment]
是1.0.0.5版本呢。试了下别的没有冒号的单集，也是无法下载。

**Comment by LGiki** [comment]
请问你使用的 Chrome 版本号是多少？

**Comment by coastguardsman** [comment]
Version 128.0.6613.138 (Official Build) (x86_64) 应该是这个吧。

**Comment by LGiki** [comment]
这个版本的 Chrome 浏览器应该是没问题才对…最后麻烦你在你刚刚提到的那个小宇宙[单集页面](https://xiaoyuzhoufm.com/episode/66d09be4d06ec988f2cbb2ad)，先在页面上任意区域右键，选择`检查`，然后在弹出的开发者工具中，切换到 `console` 面板（在中文版本里，这个面板的名字应该是叫`控制台`），这时候再点击任意一个下载按钮，看看 `console` 面板是否有出现红色的报错信息，截图给我，就像这样：
<img width="439" alt="image" src="https://github.com/user-attachments/assets/2a203db6-9001-4d9e-9d26-05e5a641d903">

**Comment by LGiki** [comment]
另外，还有一种可能是，因为和其他插件冲突导致这个插件无法正常工作，也可以禁用其他插件之后再尝试看看能否正常下载

**Comment by coastguardsman** [comment]
确实！终于正常下载了，感谢！

**Comment by LGiki** [comment]
能告诉我是禁用了哪个插件之后才恢复的吗？我也来检查一下是什么原因，看看有没有办法让两个插件共存

**Comment by coastguardsman** [comment]
可能是user-agent switcher for chrome,我直接把它remove了。其他都是on

**Comment by LGiki** [comment]
好的，谢谢，我之后找时间检查一下，这个 issue 我就先关闭啦～
